execute pathogen#infect()
set nu
syntax on
set autoindent
filetype plugin indent on
set mouse=a
set nowrap
set backspace=indent,eol,start
set copyindent
set shiftwidth=4
set shiftround
set showmatch
set ignorecase
set smarttab
set hlsearch
set incsearch
set history=1000
set undolevels=1000
set wildignore=*.swp,*.bak,*.pyc,*.class
set title
set visualbell
set noerrorbells
set nobackup
set noswapfile
set wildignore=*.o,*~,*.pyc
set ruler
set incsearch
set magic
set mat=2
set pastetoggle=<F2>
